### PR TITLE
Fix to get threshold 0 working as documented

### LINKED ISSUE #642: Threshold 0 not working as documented
### Describe the bug

Threshold section on documentation mentions following:
> In this case, the threshold property is set to 0, which means that only the document containing the "slim fit" keywords will be returned. This applies to all the document properties; if a keyword is found in a property, and another keyword is found in a different property, the document will be returned.

Meaning that if threshold is set to 0 only the documents that have both keywords "slim" and "fit" will be returned. I noticed few cases where this was not true.

When using threshold 0, the search results sometimes included documents that didn't actually have both searched keywords but their score was higher than the ones that did have. This was probably due to the length difference of these documents, one of them was short and one of them was super long. Meaning the super long document got better score even if only one search term was found.

I tried to figure out why this happens and found out that in the comments [algorithms.ts](https://github.com/oramasearch/orama/blob/main/packages/orama/src/components/algorithms.ts#L60C3-L72C4) we are making an assumption that 
>   // Find the index of the last result with all keywords.
  // Note that since score is multipled by 1.5 any time the token is encountered in results it means
  // that tokenScores and tokenKeywordsCount should always have the same order.

So we are trusting that `tokenScores` and `tokenKeywordsCount` are similarly sorted. Then we find the index of last item index in `tokenKeywordsCount` where tokenKeywordCount is equal to `keywordsCount`

Then this index is used to slice the results array, which goes wrong because sometimes the tokenScores and tokenKeywordsCount are not in same order.

While investigating this I also encountered this issue #641 

### To Reproduce

I made an simple example here https://replit.com/@valstu/FunctionalSpiffyPolygon#index.js This example indexes two documents, one long and one short one. 

Run the index files to see the search results. Threshold is set to 0, one would expect the search to return the short file since it contains both of the keywords, as defined in documentation.

### Expected behavior

When threshold is set to 0 you would expect the search to return only documents that have all the keywords, how ever this is not the case everytime.

### Environment Info

```bash
OS: Replit
Node: 20.10.0
Orama: 2.0.7
```

### Affected areas

Search

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valstu**
This PR is a suggestion to fix #642. Instead of two sets, one for token counts and one for scores we combine them into a single set. Now when sorting the list it guarantees that they're in right order. Read further information and try the test case of a bug on Replit, mentioned in the issue #642

### CODE REVIEW

**Comment by valstu** [comment]
Let me know what you think

**Comment by micheleriva** [comment]
@allevo can you please take a look at this?

**Review by micheleriva — APPROVED** [review]
That's actually a neat fix. I like the approach

File: packages/orama/src/components/algorithms.ts [hunk 1]
```diff
@@ -80,9 +89,14 @@ export function prioritizeTokenScores(
     lastTokenWithAllKeywords = 0
   }
 
+  const resultsWithIdAndScore: [number, number][] = [];
+  for (let i = 0; i < keywordsPerToken.length; i++) {
+    resultsWithIdAndScore.push([keywordsPerToken[i][0], keywordsPerToken[i][1]]);
+  }
+
```
Comment (allevo) [inline packages/orama/src/components/algorithms.ts:96]:
```suggestion
  const resultsWithIdAndScore: [number, number][] = new Array(keywordsPerToken.length);
  for (let i = 0; i < keywordsPerToken.length; i++) {
    resultsWithIdAndScore[i] = [keywordsPerToken[i][0], keywordsPerToken[i][1]];
  }
```

suggestion for better performance

File: packages/orama/src/components/algorithms.ts [hunk 2]
```diff
@@ -80,9 +89,14 @@ export function prioritizeTokenScores(
     lastTokenWithAllKeywords = 0
   }
 
+  const resultsWithIdAndScore: [number, number][] = [];
+  for (let i = 0; i < keywordsPerToken.length; i++) {
+    resultsWithIdAndScore.push([keywordsPerToken[i][0], keywordsPerToken[i][1]]);
+  }
```
Comment (allevo) [inline packages/orama/src/components/algorithms.ts:95]:
```suggestion
  const resultsWithIdAndScore: [number, number][] = new Array(keywordsPerToken.length);
  for (let i = 0; i < keywordsPerToken.length; i++) {
    resultsWithIdAndScore[i] = [keywordsPerToken[i][0], keywordsPerToken[i][1]];

```

**Comment by allevo** [comment]
I put a comment, but generally, it is ok for me!
Thanks!

**Comment by valstu** [comment]
> I put a comment, but generally, it is ok for me! Thanks!

Added changes, thanks!

File: packages/orama/src/components/algorithms.ts [hunk 3]
```diff
@@ -89,10 +89,10 @@ export function prioritizeTokenScores(
     lastTokenWithAllKeywords = 0
   }
 
-  const resultsWithIdAndScore: [number, number][] = [];
+  const resultsWithIdAndScore: [number, number][] = new Array(keywordsPerToken.length);
   for (let i = 0; i < keywordsPerToken.length; i++) {
-    resultsWithIdAndScore.push([keywordsPerToken[i][0], keywordsPerToken[i][1]]);
-  }
```
Comment (micheleriva) [inline packages/orama/src/components/algorithms.ts]: Missing closing bracket here :)

Comment (valstu) [reply packages/orama/src/components/algorithms.ts]: yeah, just  a sec :)

**Comment by micheleriva** [comment]
Thank you @valstu , will release this in a few hours.
